site_name: Gatecheck for Amazon ECS and AWS Fargate
docs_dir: 'docs/'
copyright: 'Copyright &copy; Amazon 2023'
site_author: 'AWS'
site_url: 'https://arvindsoni80.github.io/gatecheck'
repo_name: 'gatecheck'
repo_url: 'https://github.com/arvindsoni80/gatecheck'
nav:
  - Home: index.md
theme: readthedocs